/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWarrantyRouteImport } from './routes/_app/warranty'
import { Route as AppVendorsRouteImport } from './routes/_app/vendors'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppQrTrackingRouteImport } from './routes/_app/qr-tracking'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMaintenanceRouteImport } from './routes/_app/maintenance'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppGatePassRouteImport } from './routes/_app/gate-pass'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDisposalRouteImport } from './routes/_app/disposal'
import { Route as AppDepreciationRouteImport } from './routes/_app/depreciation'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditTrailRouteImport } from './routes/_app/audit-trail'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppAllocationRouteImport } from './routes/_app/allocation'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarrantyRoute = AppWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQrTrackingRoute = AppQrTrackingRouteImport.update({
  id: '/qr-tracking',
  path: '/qr-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppGatePassRoute = AppGatePassRouteImport.update({
  id: '/gate-pass',
  path: '/gate-pass',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDisposalRoute = AppDisposalRouteImport.update({
  id: '/disposal',
  path: '/disposal',
  getParentRoute: () => AppRoute,
} as any)
const AppDepreciationRoute = AppDepreciationRouteImport.update({
  id: '/depreciation',
  path: '/depreciation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditTrailRoute = AppAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAllocationRoute = AppAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/allocation': typeof AppAllocationRoute
  '/assets': typeof AppAssetsRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/dashboard': typeof AppDashboardRoute
  '/depreciation': typeof AppDepreciationRoute
  '/disposal': typeof AppDisposalRoute
  '/employees': typeof AppEmployeesRoute
  '/gate-pass': typeof AppGatePassRoute
  '/locations': typeof AppLocationsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/notifications': typeof AppNotificationsRoute
  '/qr-tracking': typeof AppQrTrackingRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/transfers': typeof AppTransfersRoute
  '/vendors': typeof AppVendorsRoute
  '/warranty': typeof AppWarrantyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/allocation': typeof AppAllocationRoute
  '/assets': typeof AppAssetsRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/dashboard': typeof AppDashboardRoute
  '/depreciation': typeof AppDepreciationRoute
  '/disposal': typeof AppDisposalRoute
  '/employees': typeof AppEmployeesRoute
  '/gate-pass': typeof AppGatePassRoute
  '/locations': typeof AppLocationsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/notifications': typeof AppNotificationsRoute
  '/qr-tracking': typeof AppQrTrackingRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/transfers': typeof AppTransfersRoute
  '/vendors': typeof AppVendorsRoute
  '/warranty': typeof AppWarrantyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/allocation': typeof AppAllocationRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/audit-trail': typeof AppAuditTrailRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/depreciation': typeof AppDepreciationRoute
  '/_app/disposal': typeof AppDisposalRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/gate-pass': typeof AppGatePassRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/qr-tracking': typeof AppQrTrackingRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/warranty': typeof AppWarrantyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/allocation'
    | '/assets'
    | '/audit-trail'
    | '/dashboard'
    | '/depreciation'
    | '/disposal'
    | '/employees'
    | '/gate-pass'
    | '/locations'
    | '/maintenance'
    | '/notifications'
    | '/qr-tracking'
    | '/reports'
    | '/settings'
    | '/transfers'
    | '/vendors'
    | '/warranty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/allocation'
    | '/assets'
    | '/audit-trail'
    | '/dashboard'
    | '/depreciation'
    | '/disposal'
    | '/employees'
    | '/gate-pass'
    | '/locations'
    | '/maintenance'
    | '/notifications'
    | '/qr-tracking'
    | '/reports'
    | '/settings'
    | '/transfers'
    | '/vendors'
    | '/warranty'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/_app/allocation'
    | '/_app/assets'
    | '/_app/audit-trail'
    | '/_app/dashboard'
    | '/_app/depreciation'
    | '/_app/disposal'
    | '/_app/employees'
    | '/_app/gate-pass'
    | '/_app/locations'
    | '/_app/maintenance'
    | '/_app/notifications'
    | '/_app/qr-tracking'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/transfers'
    | '/_app/vendors'
    | '/_app/warranty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/warranty': {
      id: '/_app/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof AppWarrantyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr-tracking': {
      id: '/_app/qr-tracking'
      path: '/qr-tracking'
      fullPath: '/qr-tracking'
      preLoaderRoute: typeof AppQrTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gate-pass': {
      id: '/_app/gate-pass'
      path: '/gate-pass'
      fullPath: '/gate-pass'
      preLoaderRoute: typeof AppGatePassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disposal': {
      id: '/_app/disposal'
      path: '/disposal'
      fullPath: '/disposal'
      preLoaderRoute: typeof AppDisposalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depreciation': {
      id: '/_app/depreciation'
      path: '/depreciation'
      fullPath: '/depreciation'
      preLoaderRoute: typeof AppDepreciationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-trail': {
      id: '/_app/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AppAuditTrailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/allocation': {
      id: '/_app/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AppAllocationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAllocationRoute: typeof AppAllocationRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAuditTrailRoute: typeof AppAuditTrailRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepreciationRoute: typeof AppDepreciationRoute
  AppDisposalRoute: typeof AppDisposalRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppGatePassRoute: typeof AppGatePassRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppQrTrackingRoute: typeof AppQrTrackingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppWarrantyRoute: typeof AppWarrantyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllocationRoute: AppAllocationRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAuditTrailRoute: AppAuditTrailRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepreciationRoute: AppDepreciationRoute,
  AppDisposalRoute: AppDisposalRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppGatePassRoute: AppGatePassRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppQrTrackingRoute: AppQrTrackingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppWarrantyRoute: AppWarrantyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
